title: WVTRA
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Creating a more neighbourly village and a safe, beautiful place to live.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.walbottlevillagetra.co.uk/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
author: Walbottle Village Tenants &amp; Residents Association Website

# Build settings
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-include-cache 
  - jekyll-minifier
include:
  - _pages

permalink: pretty

exclude: [README.md]
